USE [CQRSAVALIACAO]
GO
/****** Object:  Table [dbo].[IMPORTACAO]    Script Date: 28/12/2021 10:43:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPORTACAO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATACADASTRO] [datetime] NOT NULL,
 CONSTRAINT [PK_IMPORTACAO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IMPORTACAO_PRODUTO]    Script Date: 28/12/2021 10:43:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IMPORTACAO_PRODUTO](
	[PRODUTO_ID] [int] NOT NULL,
	[IMPORTACAO_ID] [int] NOT NULL,
 CONSTRAINT [imp_prod_pk] PRIMARY KEY CLUSTERED 
(
	[PRODUTO_ID] ASC,
	[IMPORTACAO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUTO]    Script Date: 28/12/2021 10:43:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUTO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[QUANTIDADE] [int] NOT NULL,
	[DATAENTREGA] [datetime] NOT NULL,
	[VALOR] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IMPORTACAO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_importacao] FOREIGN KEY([IMPORTACAO_ID])
REFERENCES [dbo].[IMPORTACAO] ([ID])
GO
ALTER TABLE [dbo].[IMPORTACAO_PRODUTO] CHECK CONSTRAINT [FK_importacao]
GO
ALTER TABLE [dbo].[IMPORTACAO_PRODUTO]  WITH CHECK ADD  CONSTRAINT [FK_prod] FOREIGN KEY([PRODUTO_ID])
REFERENCES [dbo].[PRODUTO] ([ID])
GO
ALTER TABLE [dbo].[IMPORTACAO_PRODUTO] CHECK CONSTRAINT [FK_prod]
GO
